name: ci-security-build

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  semgrep:
    name: Static Analysis (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: "1"

      - name: Upload Semgrep report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  build-and-scan:
    name: Build & Scan Container (Trivy)
    runs-on: ubuntu-latest
    needs: [semgrep]
    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase image name
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image (no push yet)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          push: false

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '1'

      - name: Upload Trivy report
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy.sarif

  push-on-pass:
    name: Push Image to GHCR
    runs-on: ubuntu-latest
    needs: [build-and-scan]
    if: ${{ needs.build-and-scan.result == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase image name
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
